import appleBackground from '../ativos/imagens/empresas/apple-background.webp'
import appleLogo from '../ativos/imagens/empresas/apple-logo.webp'
import microsoftBackground from '../ativos/imagens/empresas/microsoft-background.webp'
import microsoftLogo from '../ativos/imagens/empresas/microsoft-logo.webp'
import nexaCloudBackground from '../ativos/imagens/empresas/nexacloud-background.png'
import trilumLogo from '../ativos/imagens/logo-plataforma.png'

export const empresas = [
  {
    id: 'empresa-1',
    tipo: 'empresa',
    nome: 'NexaCloud Solutions',
    email: 'empresa.demo@trilum.demo',
    senha: 'Empresa@123',
    nomeOficial: 'NexaCloud Solutions Tecnologia Ltda.',
    logo: 'NC',
    logoUrl: trilumLogo,
    capaUrl: nexaCloudBackground,
    capa: 'linear-gradient(120deg, rgba(15, 23, 42, 0.98), rgba(37, 99, 235, 0.86), rgba(20, 184, 166, 0.72))',
    descricao:
      'A NexaCloud Solutions é uma empresa fictícia de tecnologia focada em desenvolvimento de software, cloud computing, automação e modernização de sistemas. Atua com squads multidisciplinares para construir aplicações web, APIs, dashboards e soluções em nuvem para empresas em crescimento. Seu ambiente valoriza aprendizado contínuo, colaboração, documentação técnica e evolução de talentos em início de carreira.',
    descricaoCurta:
      'Criamos soluções digitais em cloud, automação e engenharia de software para transformar processos em produtos escaláveis.',
    setor: 'Tecnologia, Cloud e Desenvolvimento de Software',
    tamanho: '120-300 colaboradores',
    sede: 'Recife, PE',
    localizacao: 'Recife, PE',
    hub: 'Porto Digital - Bairro do Recife, Recife - PE',
    especialidades: [
      'Cloud Computing',
      'Desenvolvimento Web',
      'APIs REST',
      'DevOps',
      'Dados',
      'Automação',
      'UX',
      'QA',
    ],
    stackDetalhes: [
      'Cloud & DevOps: Docker, Docker Compose, Linux, CI/CD e serviços em nuvem.',
      'Back-end: Node.js, Java, Spring Boot, APIs REST e bancos SQL.',
      'Front-end: React, TypeScript, Tailwind CSS e Design System.',
      'Dados: Python, dashboards, análise de indicadores e integração com APIs.',
      'Qualidade: testes manuais, automação com Playwright e revisão de entregas.',
    ],
    beneficios: [
      'Mentoria para pessoas em início de carreira',
      'Projetos reais em squads multidisciplinares',
      'Cultura de documentação',
      'Incentivo a certificações',
      'Modelo híbrido em Recife',
      'Trilhas internas de aprendizado',
      'Feedback contínuo',
      'Ambiente colaborativo',
    ],
    site: 'https://nexacloud.demo',
    instagram: 'https://instagram.com/nexacloud.demo',
    linkedin: 'https://linkedin.com/company/nexacloud-demo',
    youtube: 'https://youtube.com/@nexaclouddemo',
  },
  {
    id: 'empresa-2',
    nome: 'Nova Jornada Digital',
    logo: 'NJ',
    capa: 'linear-gradient(120deg, rgba(15, 23, 42, 0.95), rgba(99, 102, 241, 0.76))',
    descricao:
      'Consultoria de produtos digitais com foco em inclusão, desenvolvimento web e squads multidisciplinares.',
    localizacao: 'Remoto',
    site: 'https://novajornada.dev',
  },
  {
    id: 'empresa-microsoft',
    nome: 'Microsoft Brasil',
    nomeOficial: 'Microsoft Informatica Ltda.',
    logo: 'MS',
    logoUrl: microsoftLogo,
    capaUrl: microsoftBackground,
    capa: 'linear-gradient(120deg, rgba(0, 78, 140, 0.96), rgba(0, 188, 242, 0.7))',
    descricaoCurta: 'Nossa missao e empoderar cada pessoa e cada organizacao no planeta a conquistar mais.',
    descricao:
      'Lider mundial em software, servicos, dispositivos e solucoes que ajudam pessoas e empresas a atingirem seu potencial pleno. Focada em transformacao digital atraves de nuvem inteligente e borda inteligente.',
    setor: 'Tecnologia e Software',
    tamanho: '220.000+ funcionarios no mundo',
    sede: 'Sao Paulo, SP',
    localizacao: 'Sao Paulo, SP',
    hub: 'Microsoft Reactor (Polo de Inovacao)',
    especialidades: ['Azure', 'Inteligencia Artificial', 'Windows', 'Xbox', 'Microsoft 365', 'LinkedIn'],
    stackDetalhes: [
      'Ecossistema .NET, C# e TypeScript em produtos corporativos.',
      'Python, Kubernetes e SQL Server em ambientes de dados e cloud.',
      'Azure, DevOps e seguranca em escala enterprise.',
    ],
    beneficios: [
      'Carreira global',
      'Vale-refeicao flexivel',
      'Plano de saude premium',
      'Auxilio Home Office',
      'Licenca parental estendida',
    ],
    site: 'https://www.microsoft.com/pt-br',
    linkedin: 'https://www.linkedin.com/company/microsoft/',
  },
  {
    id: 'empresa-apple',
    nome: 'Apple Brasil',
    nomeOficial: 'Apple Computer Brasil Ltda.',
    logo: 'AP',
    logoUrl: appleLogo,
    capaUrl: appleBackground,
    capa: 'linear-gradient(120deg, rgba(17, 24, 39, 0.96), rgba(120, 144, 156, 0.72))',
    descricaoCurta: 'Onde criadores constroem o futuro da tecnologia.',
    descricao:
      'A Apple revolucionou a tecnologia pessoal com o Macintosh e hoje lidera o mundo em inovacao com iPhone, iPad, Mac e Apple Watch, alem de sistemas operacionais e servicos como iCloud e Apple Music.',
    setor: 'Eletronicos e Software',
    tamanho: '160.000+ funcionarios no mundo',
    sede: 'Sao Paulo, SP',
    localizacao: 'Sao Paulo, SP',
    hub: 'Apple Academy (Inovacao e Educacao)',
    especialidades: ['iOS', 'macOS', 'Design de Hardware', 'Silicio Apple', 'UX', 'Privacidade'],
    stackDetalhes: [
      'Swift, SwiftUI e Objective-C em aplicativos nativos.',
      'C++, Core ML e Machine Learning para performance e inteligencia embarcada.',
      'Design, acessibilidade e privacidade como base da experiencia.',
    ],
    beneficios: [
      'Descontos em produtos',
      'Plano de acoes para funcionarios',
      'Academia no local',
      'Cultura de excelencia',
      'Seguro de vida',
    ],
    site: 'https://www.apple.com/br/',
    linkedin: 'https://www.linkedin.com/company/apple/',
  },
]
