import {
  aulasAlgoritmos,
  aulasEmpregabilidade,
  aulasFrontHtmlCssProjeto,
  aulasFrontLandingPage,
  aulasGitEquipes,
  aulasGitGithub,
  aulasGithubPortfolio,
  aulasInformaticaModulo1,
  aulasInformaticaModulo2,
  aulasJavascriptCompleto,
  aulasJavascriptDom,
  aulasLinkedin,
  aulasMySQL,
  aulasNodeApi,
  aulasNodeCrud,
  aulasOratoria,
  aulasPythonBasico,
  cursos,
  cursosInseridos,
  modulosReactBasico,
  modulosReactIntermediario,
  modulosPythonAnalise,
  modulosJavaBasico,
  modulosJavaSpring,
  modulosInglesTecnico,
  modulosPortfolioEntrevista,
  modulosQaCompleto,
} from './cursos'
import { duracaoDosCursos, minutosParaDuracao } from '../servicos/duracao'

const videos = {
  informatica: 'https://www.youtube.com/embed/6UQMWqZjd0U',
  algoritmos: 'https://www.youtube.com/embed/videoseries?list=PLHz_AreHm4dmSj0MHol_aoNYCSGFqvfXV',
  javascript: 'https://www.youtube.com/embed/Ptbk2af68e8',
  react: 'https://www.youtube.com/embed/2RWsLmu8yVc',
  node: 'https://www.youtube.com/embed/IOfDoyP1Aq0',
  java: 'https://www.youtube.com/embed/sTX0UEplF54',
  go: 'https://www.youtube.com/embed/8uiZC0l4Ajw',
  python: 'https://www.youtube.com/embed/S9uPNppGsGo',
  sql: 'https://www.youtube.com/embed/Ofktsne-utM',
  git: 'https://www.youtube.com/embed/DqTITcMq68k',
  gitPratica: 'https://www.youtube.com/embed/UBAX-13g8OM',
  docker: 'https://www.youtube.com/embed/0cDj7citEjE',
  qa: 'https://www.youtube.com/embed/5S7YP0SQ_eU',
  ingles: 'https://www.youtube.com/embed/4cQjNw0gqys',
  carreira: 'https://www.youtube.com/embed/6p9Il_j0zjc',
}

function aula(id, titulo, duracao, videoUrl, descricao, professor = 'Professor externo', capitulos = []) {
  return { id, titulo, duracao, videoUrl, descricao, professor, capitulos }
}

function cursoInseridoPorId(id) {
  return cursosInseridos.find((curso) => curso.id === id)
}

function cursoPorId(id) {
  return cursos.find((curso) => curso.id === id)
}

function cursosPorIds(ids) {
  return ids
    .map((id) => {
      const curso = cursoPorId(id)

      if (!curso && import.meta.env?.DEV) {
        console.warn(`Curso não encontrado para trilha: ${id}`)
      }

      return curso
    })
    .filter(Boolean)
}

function duracaoDeCursos(ids) {
  return minutosParaDuracao(duracaoDosCursos(cursosPorIds(ids)))
}

function modulosDoCurso(id) {
  const curso = cursoPorId(id)
  if (!curso) return []

  if (Array.isArray(curso.modulos) && curso.modulos.length) {
    return curso.modulos.map((modulo, indice) => ({
      ...modulo,
      id: modulo.id || `${id}-modulo-${indice + 1}`,
      cursoId: id,
      cursoTitulo: curso.titulo,
      descricao: modulo.descricao || curso.destaque || curso.descricao,
      aulas: modulo.aulas || [],
    }))
  }

  return [{
    id: `${id}-jornada`,
    cursoId: id,
    cursoTitulo: curso.titulo,
    titulo: curso.titulo,
    descricao: curso.destaque || curso.descricao,
    aulas: curso.aulas || [],
  }]
}

function modulosDeCursos(ids) {
  return ids.flatMap(modulosDoCurso)
}

function criarTrilhaComCursos({ cursoIds = [], duracao, ...trilha }) {
  const duracaoCalculada = duracaoDeCursos(cursoIds)

  return {
    ...trilha,
    duracao: duracaoCalculada || duracao || '0m',
    cursoIds,
    modulos: modulosDeCursos(cursoIds),
  }
}

const cursoAngular = cursoInseridoPorId('curso-angular-basico')
const cursoPhp = cursoInseridoPorId('curso-php-iniciante')

export const trilhas = [
  {
    id: 'informatica-essencial',
    titulo: 'Informática Essencial',
    categoria: 'Fundamentos',
    area: 'fundamentos',
    nivel: 'Iniciante',
    duracao: '10h30',
    tempoSugerido: '2 semanas',
    tecnologias: ['informatica'],
    ordemBase: 1,
    tags: ['informatica', 'iniciante', 'windows', 'fundamentos', 'autonomia-digital'],
    descricao: 'Ganhe autonomia no computador antes de entrar em lógica e programação.',
    destaque: 'Comece pelo básico sem pular etapas.',
    modulos: [
      {
        id: 'info-fundamentos',
        titulo: 'Nível 1: Informática básica',
        descricao: 'Fundamentos do computador, componentes, periféricos e noções essenciais.',
        aulas: aulasInformaticaModulo1,
      },
      {
        id: 'info-pratica',
        titulo: 'Nível 2: Windows e sistema operacional',
        descricao: 'Windows, instalação, contas, arquivos, segurança e otimização básica.',
        aulas: aulasInformaticaModulo2,
      },
    ],
  },
  {
    id: 'logica-algoritmos',
    titulo: 'Lógica de Programação e Algoritmos',
    categoria: 'Programação',
    area: 'fundamentos',
    nivel: 'Iniciante',
    duracao: '9h',
    tempoSugerido: '6 semanas',
    tecnologias: ['logica'],
    ordemBase: 2,
    tags: ['logica', 'algoritmos', 'iniciante', 'portugol', 'base'],
    descricao: 'Base para entender variáveis, operadores, condições, repetições, funções, vetores e matrizes.',
    destaque: 'Base recomendada antes de escolher uma linguagem.',
    modulos: [
      {
        id: 'algoritmo-base',
        titulo: 'Nível 1: Introdução e primeiros algoritmos',
        descricao: 'O primeiro contato com raciocínio computacional, operadores e exercícios iniciais.',
        aulas: aulasAlgoritmos.slice(0, 6),
      },
      {
        id: 'algoritmo-estruturas',
        titulo: 'Nível 2: Condicionais e repetição',
        descricao: 'Decisões, laços de repetição e resolução de problemas com fluxo de controle.',
        aulas: aulasAlgoritmos.slice(6, 11),
      },
      {
        id: 'algoritmo-organizacao',
        titulo: 'Nível 3: Funções, vetores e matrizes',
        descricao: 'Organização de código e estruturas para lidar com conjuntos de dados.',
        aulas: aulasAlgoritmos.slice(11),
      },
      {
        id: 'python-primeiros-passos',
        titulo: 'Nível 4: Python básico',
        descricao: 'Primeiro contato com uma linguagem real depois da lógica.',
        aulas: aulasPythonBasico,
      },
    ],
  },
  {
    id: 'git-github',
    titulo: 'Git e GitHub para Projetos',
    categoria: 'Ferramentas',
    area: 'fundamentos',
    nivel: 'Iniciante',
    duracao: '2h25',
    tempoSugerido: '3 semanas',
    tecnologias: ['git-github'],
    ordemBase: 3,
    tags: ['git', 'github', 'portfolio', 'versionamento', 'fundamentos'],
    descricao: 'Aprenda Git e GitHub com conceitos essenciais e uma prática completa do primeiro commit ao pull request.',
    destaque: 'Essencial para portfólio e trabalho em equipe.',
    modulos: [
      {
        id: 'git-base',
        titulo: 'Nível 1: Versionamento',
        descricao: 'Conceitos, repositório local e base para trabalhar com versionamento.',
        aulas: aulasGitGithub.slice(0, 1),
      },
      {
        id: 'git-portfolio',
        titulo: 'Nível 2: GitHub na prática',
        descricao: 'Repositório remoto, commits, branch, fork, pull request e publicação.',
        aulas: aulasGitGithub.slice(1),
      },
      {
        id: 'git-equipes',
        titulo: 'Nível 3: Trabalho em equipe',
        descricao: 'Fluxo profissional para usar Git e GitHub em equipes de programação.',
        aulas: aulasGitEquipes,
      },
      {
        id: 'github-portfolio-extra',
        titulo: 'Extra: GitHub como portfólio',
        descricao: 'Personalize seu perfil no GitHub para apresentar melhor seus projetos e habilidades.',
        aulas: aulasGithubPortfolio,
      },
    ],
  },
  {
    id: 'javascript-frontend',
    titulo: 'Front-end com HTML, CSS e JavaScript',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Basico',
    duracao: '26h',
    tempoSugerido: '5 semanas',
    tecnologias: ['javascript', 'html', 'css'],
    ordemBase: 4,
    tags: ['javascript', 'frontend', 'html', 'css', 'dom', 'portfolio'],
    descricao: 'Construa interfaces, manipule páginas e crie primeiras telas profissionais.',
    destaque: 'Ideal para quem quer criar telas e portfólio.',
    modulos: [
      {
        id: 'front-html-css-projeto',
        titulo: 'Nível 1: HTML e CSS com projeto',
        descricao: 'Fundamentos de HTML, CSS, responsividade e um projeto prático para fixar a base.',
        aulas: aulasFrontHtmlCssProjeto,
      },
      {
        id: 'front-landing-page',
        titulo: 'Nível 2: Landing page com HTML, CSS e JavaScript',
        descricao: 'Projeto completo em sete aulas para construir uma página de inscrição responsiva.',
        aulas: aulasFrontLandingPage,
      },
      {
        id: 'front-js-completo',
        titulo: 'Nível 3: JavaScript completo para iniciantes',
        descricao: 'Variáveis, objetos, arrays, funções, condicionais, laços, DOM e mini-projetos.',
        aulas: aulasJavascriptCompleto,
      },
      {
        id: 'front-js-dom',
        titulo: 'Nível 4: DOM, arrays, objetos e formulários',
        descricao: 'Eventos, manipulação da página, arrays, objetos e iteração para interfaces mais reais.',
        aulas: aulasJavascriptDom,
      },
    ],
  },
  {
    id: 'react-frontend',
    titulo: 'React para Front-end',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Intermediário',
    duracao: '8h47',
    tempoSugerido: '6 semanas',
    tecnologias: ['react', 'javascript'],
    ordemBase: 5,
    tags: ['react', 'frontend', 'componentes', 'router', 'spa', 'portfolio', 'sass', 'deploy'],
    descricao: 'Evolua de JavaScript para componentes, estado, rotas, integração com API, portfólio com SASS e deploy.',
    destaque: 'Próximo passo natural depois de JavaScript e DOM.',
    modulos: [
      ...modulosReactBasico,
      ...modulosReactIntermediario,
    ],
  },
  {
    id: 'angular-frontend',
    titulo: 'Angular para Front-end',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Intermediario',
    duracao: cursoAngular?.duracao || '6h37',
    tempoSugerido: '6 semanas',
    tecnologias: ['angular', 'javascript', 'typescript'],
    ordemBase: 6,
    tags: ['angular', 'frontend', 'typescript', 'javascript', 'spa', 'testes', 'docker', 'deploy', 'ci-cd', 'portfolio'],
    descricao: 'Construa uma aplicacao moderna com Angular, componentes, Signals, formularios, testes, Docker e deploy.',
    destaque: 'Boa escolha para quem quer front-end estruturado e projetos completos.',
    modulos: cursoAngular?.modulos || [],
    thumbnailUrl: cursoAngular?.thumbnailUrl,
  },
  {
    id: 'node-backend',
    titulo: 'Back-end com Node.js',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Básico',
    duracao: '2h43',
    tempoSugerido: '5 semanas',
    tecnologias: ['node', 'javascript'],
    ordemBase: 7,
    tags: ['node', 'backend', 'api', 'javascript', 'express', 'mongodb', 'crud'],
    descricao: 'Crie APIs com JavaScript, Express e MongoDB, organize rotas e pratique CRUD.',
    destaque: 'Boa ponte para quem vem do front-end.',
    modulos: [
      {
        id: 'node-api',
        titulo: 'Nível 1: API do zero com Node.js',
        descricao: 'Servidor, rotas, parâmetros, MongoDB, edição, remoção e testes básicos.',
        aulas: aulasNodeApi,
      },
      {
        id: 'node-crud-ingles',
        titulo: 'Nível 2: CRUD API em inglês',
        descricao: 'Node, Express, MongoDB, testes de API, rotas, controllers e push para o GitHub.',
        aviso: 'Conteúdo em inglês: recomendado para quem já consegue acompanhar termos técnicos ou quer treinar inglês para programação.',
        aulas: aulasNodeCrud,
      },
    ],
  },
  {
    id: 'java-spring',
    titulo: 'Back-end com Java e Spring Boot',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediário',
    duracao: '12h23',
    tempoSugerido: '8 semanas',
    tecnologias: ['java'],
    ordemBase: 8,
    tags: ['java', 'backend', 'spring', 'api', 'poo', 'jpa', 'security', 'jwt'],
    descricao: 'Aprenda Java do básico à orientação a objetos e avance para APIs REST com Spring Boot, JPA, Hibernate, Spring Security e JWT.',
    destaque: 'Boa evolução para quem quer mirar vagas back-end júnior com Java.',
    modulos: [
      ...modulosJavaBasico,
      ...modulosJavaSpring,
    ],
  },
  criarTrilhaComCursos({
    id: 'backend-java-profissional',
    titulo: 'Back-end Java Profissional',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    tempoSugerido: '16 semanas',
    tecnologias: ['java', 'sql', 'git-github', 'docker-cloud'],
    ordemBase: 30,
    tags: [
      'java',
      'spring',
      'backend',
      'api',
      'api-rest',
      'sql',
      'junit',
      'mockito',
      'arquitetura',
      'mensageria',
      'docker',
      'devops',
      'seguranca',
      'portfolio',
    ],
    descricao:
      'Uma jornada completa para sair da base e construir repertorio profissional em Java, APIs, banco de dados, testes, arquitetura, mensageria, DevOps e seguranca.',
    destaque: 'Caminho robusto para quem quer evoluir em back-end Java com projetos reais.',
    cursoIds: [
      'curso-logica-zero',
      'curso-git-github',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-sql-consultas',
      'curso-java-poo',
      'curso-java-spring-api',
      'curso-spring-boot-api-erudio',
      'curso-testes-unitarios-junit-mockito',
      'curso-design-patterns-poo',
      'curso-arquitetura-limpa-java',
      'curso-mensageria-microservices',
      'curso-docker-basico',
      'devops-cloud-ci-cd',
      'seguranca-software-owasp',
      'curso-portfolio-entrevista',
    ],
  }),
  {
    id: 'php-backend',
    titulo: 'Back-end com PHP',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Basico',
    duracao: cursoPhp?.duracao || '9h30',
    tempoSugerido: '6 semanas',
    tecnologias: ['php'],
    ordemBase: 9,
    tags: ['php', 'backend', 'web', 'html', 'formularios', 'servidor', 'banco-de-dados', 'portfolio'],
    descricao: 'Aprenda PHP para criar paginas dinamicas, trabalhar com formularios, servidor e base para integracao com banco de dados.',
    destaque: 'Caminho pratico para quem quer back-end web com PHP.',
    modulos: cursoPhp?.modulos || [],
    thumbnailUrl: cursoPhp?.thumbnailUrl,
  },
  {
    id: 'go-backend',
    titulo: 'Back-end com Go',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    duracao: '26h',
    tempoSugerido: '5 semanas',
    tecnologias: ['go'],
    ordemBase: 10,
    tags: ['go', 'golang', 'backend', 'api', 'concorrencia'],
    descricao: 'Aprenda Go para construir APIs simples, performaticas e faceis de publicar.',
    destaque: 'Otima escolha para quem quer aprofundar back-end moderno.',
    modulos: [
      {
        id: 'go-base',
        titulo: 'Nivel 1: Go essencial',
        descricao: 'Sintaxe, structs, funcoes e pacotes.',
        aulas: [
          aula('go-aula-1', 'Primeiros passos com Go', '28m', videos.go, 'Configure ambiente e escreva os primeiros programas.'),
          aula('go-aula-2', 'Structs, slices e funcoes', '36m', videos.go, 'Use os blocos principais da linguagem.'),
        ],
      },
      {
        id: 'go-api',
        titulo: 'Nivel 2: APIs com Go',
        descricao: 'HTTP, handlers, JSON e projeto pratico.',
        aulas: [
          aula('go-aula-3', 'API HTTP em Go', '42m', videos.go, 'Crie endpoints com a biblioteca padrao.'),
          aula('go-aula-4', 'Projeto de API para portfolio', '50m', videos.go, 'Organize um projeto back-end simples e demonstravel.'),
        ],
      },
    ],
  },
  {
    id: 'python-dados',
    titulo: 'Python para Dados e Automação',
    categoria: 'Dados',
    area: 'dados',
    nivel: 'Intermediário',
    duracao: '32h30',
    tempoSugerido: '8 semanas',
    tecnologias: ['python'],
    ordemBase: 12,
    tags: ['python', 'dados', 'automacao', 'pandas', 'numpy', 'visualizacao', 'webscraping'],
    descricao: 'Aprenda Python com foco em fundamentos, análise de dados, pandas, Numpy, visualização, webscraping e projeto prático.',
    destaque: 'Boa opção para evoluir de Python básico para análise de dados real.',
    modulos: [
      {
        id: 'python-base',
        titulo: 'Nível 1: Python essencial',
        descricao: 'Variáveis, condicionais, laços, listas e pequenos projetos práticos.',
        aulas: aulasPythonBasico,
      },
      ...modulosPythonAnalise,
    ],
  },
  {
    id: 'sql-banco-dados',
    titulo: 'SQL e Banco de Dados',
    categoria: 'Dados',
    area: 'dados',
    nivel: 'Basico',
    duracao: '8h10',
    tempoSugerido: '4 semanas',
    tecnologias: ['sql'],
    ordemBase: 11,
    tags: ['sql', 'banco-de-dados', 'dados', 'backend', 'consultas'],
    descricao: 'Aprenda MySQL, criação de bancos, tabelas, consultas SELECT, modelo relacional, chaves estrangeiras e JOIN.',
    destaque: 'Complemento forte para dados, back-end e suporte técnico.',
    modulos: [
      {
        id: 'mysql-introducao-instalacao',
        titulo: 'Nível 1: Introdução e instalação',
        descricao: 'Entenda bancos de dados e prepare o ambiente com WAMP ou XAMPP.',
        aulas: aulasMySQL.slice(0, 3),
      },
      {
        id: 'mysql-estrutura-dados',
        titulo: 'Nível 2: Estrutura do banco',
        descricao: 'Crie bancos, melhore tabelas e pratique a base de estruturação dos dados.',
        aulas: aulasMySQL.slice(3, 6),
      },
      {
        id: 'mysql-manipulacao-admin',
        titulo: 'Nível 3: Manipulação e administração',
        descricao: 'Insira dados, altere tabelas, manipule linhas, faça backups e use o PHPMyAdmin.',
        aulas: aulasMySQL.slice(6, 12),
      },
      {
        id: 'mysql-consultas-select',
        titulo: 'Nível 4: Consultas com SELECT',
        descricao: 'Aprenda a consultar e refinar resultados com SELECT.',
        aulas: aulasMySQL.slice(12, 15),
      },
      {
        id: 'mysql-relacionamentos-joins',
        titulo: 'Nível 5: Relacionamentos e JOIN',
        descricao: 'Modelo relacional, chaves estrangeiras, JOIN e consultas com várias tabelas.',
        aulas: aulasMySQL.slice(15),
      },
    ],
  },
  criarTrilhaComCursos({
    id: 'devops-docker-cloud',
    titulo: 'DevOps Inicial com Docker e Cloud',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Basico',
    tempoSugerido: '10 semanas',
    tecnologias: ['docker-cloud', 'linux', 'git-github', 'seguranca'],
    ordemBase: 13,
    tags: ['devops', 'docker', 'docker-compose', 'linux', 'aws', 'cloud', 'ci-cd', 'deploy', 'infra', 'seguranca', 'api'],
    descricao:
      'Jornada para publicar e manter aplicacoes com Git, Linux, Docker, Docker Compose, AWS, CI/CD, seguranca e nocao de HTTP/API.',
    destaque: 'Para quem quer publicar projetos e entender ambientes de producao.',
    cursoIds: [
      'curso-git-github',
      'linux-para-iniciantes',
      'curso-docker-basico',
      'curso-cloud-deploy',
      'curso-aws-cloud-practitioner',
      'devops-cloud-ci-cd',
      'curso-seguranca-informacao-pratica',
      'seguranca-software-owasp',
      'fundamentos-http-api-web',
    ],
  }),
  criarTrilhaComCursos({
    id: 'devops-cloud-profissional',
    titulo: 'DevOps e Cloud Profissional',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Intermediario',
    tempoSugerido: '14 semanas',
    tecnologias: ['docker-cloud', 'linux', 'git-github', 'seguranca'],
    ordemBase: 34,
    tags: ['devops', 'docker', 'docker-compose', 'cloud', 'aws', 'linux', 'ci-cd', 'deploy', 'seguranca', 'portfolio'],
    descricao:
      'Jornada profissional para operar projetos com Git, Linux, Docker, cloud, AWS, CI/CD, deploy, seguranca e fundamentos de HTTP/API.',
    destaque: 'Caminho robusto para quem quer evoluir em infraestrutura, containers e cloud.',
    cursoIds: [
      'curso-git-github',
      'linux-para-iniciantes',
      'curso-docker-basico',
      'curso-cloud-deploy',
      'curso-aws-cloud-practitioner',
      'devops-cloud-ci-cd',
      'curso-seguranca-informacao-pratica',
      'seguranca-software-owasp',
      'fundamentos-http-api-web',
    ],
  }),
  criarTrilhaComCursos({
    id: 'linux-fundamentos',
    titulo: 'Linux para DevOps',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Iniciante',
    tempoSugerido: '3 semanas',
    tecnologias: ['linux', 'git-github'],
    ordemBase: 17,
    tags: ['linux', 'terminal', 'devops', 'infra', 'servidores'],
    descricao: 'Base de Linux e terminal para trabalhar melhor com servidores, deploy e ambientes de desenvolvimento.',
    destaque: 'Complemento direto para quem quer atuar com DevOps e infraestrutura.',
    cursoIds: ['linux-para-iniciantes'],
  }),
  criarTrilhaComCursos({
    id: 'seguranca-informacao',
    titulo: 'Seguranca para Projetos Web',
    categoria: 'DevOps',
    area: 'devops',
    nivel: 'Basico',
    tempoSugerido: '4 semanas',
    tecnologias: ['seguranca', 'api-rest'],
    ordemBase: 18,
    tags: ['seguranca', 'owasp', 'boas-praticas', 'api-rest', 'web', 'devops'],
    descricao: 'Fundamentos de seguranca da informacao e boas praticas OWASP para proteger sistemas web e APIs.',
    destaque: 'Ajuda a publicar e manter aplicacoes com mais cuidado e criterio.',
    cursoIds: ['curso-seguranca-informacao-pratica', 'seguranca-software-owasp'],
  }),
  criarTrilhaComCursos({
    id: 'api-http-rest',
    titulo: 'HTTP e APIs REST',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Basico',
    tempoSugerido: '3 semanas',
    tecnologias: ['api', 'api-rest'],
    ordemBase: 19,
    tags: ['http', 'api', 'api-rest', 'backend', 'qa', 'devops'],
    descricao: 'Entenda HTTP, REST, status codes, parametros, metodos e boas praticas antes de integrar, testar ou publicar APIs.',
    destaque: 'Complemento util para back-end, QA e DevOps.',
    cursoIds: ['fundamentos-http-api-web', 'curso-rest-api-fundamentos'],
  }),
  {
    id: 'qa-testes',
    titulo: 'QA e Testes para Iniciantes',
    categoria: 'QA',
    area: 'qa',
    nivel: 'Iniciante',
    duracao: '9h35',
    tempoSugerido: '4 semanas',
    tecnologias: ['qa'],
    ordemBase: 14,
    tags: ['qa', 'testes', 'qualidade', 'bugs', 'produto', 'automacao', 'api', 'mobile', 'appium'],
    descricao: 'Aprenda fundamentos de QA, cenários de teste, bugs, automação, Git, API, mobile, Appium, Jenkins e Docker.',
    destaque: 'Uma entrada prática para quem gosta de detalhe, produto e qualidade.',
    modulos: modulosQaCompleto,
  },
  criarTrilhaComCursos({
    id: 'backend-node-api-profissional',
    titulo: 'Back-end Node API Profissional',
    categoria: 'Back-end',
    area: 'backend',
    nivel: 'Intermediario',
    tempoSugerido: '12 semanas',
    tecnologias: ['node', 'javascript', 'api-rest', 'sql'],
    ordemBase: 31,
    tags: ['node', 'javascript', 'backend', 'api', 'api-rest', 'sql', 'mongodb', 'seguranca', 'docker', 'portfolio'],
    descricao: 'Jornada para construir APIs com Node, banco de dados, seguranca, Docker e portfolio.',
    destaque: 'Caminho robusto para quem conhece JavaScript e quer evoluir em APIs.',
    cursoIds: [
      'curso-git-github',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'curso-node-api',
      'curso-node-crud',
      'curso-sql-consultas',
      'curso-mongodb-basico-avancado',
      'seguranca-software-owasp',
      'curso-docker-basico',
      'curso-portfolio-entrevista',
    ],
  }),
  criarTrilhaComCursos({
    id: 'qa-automacao-profissional',
    titulo: 'QA Automacao Profissional',
    categoria: 'QA',
    area: 'qa',
    nivel: 'Intermediario',
    tempoSugerido: '10 semanas',
    tecnologias: ['qa', 'api-rest', 'git-github', 'docker-cloud'],
    ordemBase: 32,
    tags: ['qa', 'testes', 'automacao', 'cypress', 'api-rest', 'ci-cd', 'docker', 'seguranca'],
    descricao: 'Jornada de QA com testes manuais, automacao, testes de API, Git, CI/CD, Docker e seguranca basica.',
    destaque: 'Para evoluir de fundamentos de QA para automacao e rotina profissional.',
    cursoIds: [
      'curso-git-github',
      'curso-qa-manual',
      'fundamentos-http-api-web',
      'curso-rest-api-fundamentos',
      'testes-api-rest-completo',
      'curso-cypress-automacao-testes',
      'devops-cloud-ci-cd',
      'curso-docker-basico',
      'seguranca-software-owasp',
    ],
  }),
  criarTrilhaComCursos({
    id: 'frontend-angular-profissional',
    titulo: 'Front-end Angular Profissional',
    categoria: 'Front-end',
    area: 'frontend',
    nivel: 'Intermediario',
    tempoSugerido: '10 semanas',
    tecnologias: ['angular', 'typescript', 'javascript', 'design-system'],
    ordemBase: 33,
    tags: ['angular', 'typescript', 'javascript', 'frontend', 'design-system', 'testes', 'deploy', 'portfolio'],
    descricao: 'Jornada de front-end com JavaScript, TypeScript, Angular, design system, testes, deploy e portfolio.',
    destaque: 'Caminho maior para quem quer se aprofundar em Angular com projetos completos.',
    cursoIds: [
      'curso-html-css-js',
      'curso-logica-typescript',
      'curso-angular-basico',
      'curso-design-system-figma',
      'curso-git-github',
      'curso-docker-basico',
      'devops-cloud-ci-cd',
      'curso-portfolio-entrevista',
    ],
  }),
  {
    id: 'ingles-tech',
    titulo: 'Inglês para Tecnologia',
    categoria: 'Carreira',
    area: 'carreira',
    nivel: 'Iniciante',
    duracao: '1h34',
    tempoSugerido: '3 semanas',
    tecnologias: ['ingles'],
    ordemBase: 15,
    tags: ['ingles', 'programacao', 'entrevista', 'carreira', 'internacional'],
    descricao: 'Aprenda vocabulário, pronúncia, cargos em tecnologia e perguntas comuns em entrevistas em inglês.',
    destaque: 'Complemento importante para aumentar empregabilidade.',
    modulos: modulosInglesTecnico,
  },
  {
    id: 'carreira-comunicacao',
    titulo: 'Carreira, Comunicação e Portfólio',
    categoria: 'Soft skills',
    area: 'carreira',
    nivel: 'Todos',
    duracao: '9h32',
    tempoSugerido: '2 semanas',
    tecnologias: ['carreira'],
    ordemBase: 16,
    tags: ['soft-skills', 'entrevista', 'portfolio', 'retorica', 'comunicacao'],
    descricao: 'Desenvolva comunicação, site de portfólio, roteiro de entrevista, storytelling de projetos e postura profissional.',
    destaque: 'Ajuda a transformar estudo em oportunidade.',
    modulos: [
      {
        id: 'comunicacao-base',
        titulo: 'Nível 1: Oratória e comunicação',
        descricao: 'Clareza, postura, confiança e comunicação de alta performance.',
        aulas: aulasOratoria,
      },
      {
        id: 'portfolio-base',
        titulo: 'Nível 2: LinkedIn para primeira oportunidade',
        descricao: 'Perfil profissional, posicionamento e conexões estratégicas.',
        aulas: aulasLinkedin,
      },
      {
        id: 'empregabilidade-extra',
        titulo: 'Nível 3: Empregabilidade, currículo e IA',
        descricao: 'Aula especial para melhorar LinkedIn, currículo e narrativa profissional.',
        aulas: aulasEmpregabilidade,
      },
      ...modulosPortfolioEntrevista,
    ],
  },
]
