export const vagas = [
  {
    id: 'vaga-1',
    empresaId: 'empresa-1',
    titulo: 'Desenvolvedor Front-end Júnior',
    nivel: 'Júnior',
    tipo: 'CLT',
    modalidade: 'Híbrido',
    localizacao: 'Recife, PE',
    salario: 'R$ 2.800 - R$ 3.600',
    status: 'ativa',
    publicadaEm: '2026-05-26',
    candidatos: 1,
    tags: ['react', 'typescript', 'frontend', 'fluent-ui', 'azure', 'acessibilidade'],
    descricao:
      'No time de Front-end da Avanade, seu desafio será transformar designs complexos em interfaces fluidas, acessíveis e performáticas dentro do ecossistema Microsoft.',
    requisitos: [
      'HTML5, CSS3, SASS ou Styled Components e JavaScript moderno',
      'Conhecimento em TypeScript para projetos de escala',
      'Noções sólidas de React e gerenciamento de estado',
      'Git/GitHub e familiaridade com ambientes de nuvem',
      'Boa comunicação para atuar com times multidisciplinares',
    ],
    atividades: [
      'Criar interfaces responsivas com React e Fluent UI',
      'Integrar APIs RESTful e fluxos de dados com Azure Functions',
      'Participar de code reviews e apoiar boas práticas de acessibilidade',
      'Atuar em squads globais usando metodologias ágeis e Azure DevOps',
    ],
  },
  {
    id: 'vaga-6',
    empresaId: 'empresa-1',
    titulo: 'Analista de Suporte Técnico Júnior',
    nivel: 'Júnior',
    tipo: 'CLT',
    modalidade: 'Presencial',
    localizacao: 'Recife, PE',
    salario: 'R$ 2.200 - R$ 2.900',
    status: 'ativa',
    publicadaEm: '2026-05-26',
    candidatos: 1,
    tags: ['suporte', 'microsoft-365', 'azure', 'redes', 'itil'],
    descricao:
      'Apoiar usuários internos e equipes de projeto em rotinas de suporte, ambientes Microsoft 365, chamados técnicos e documentação de soluções.',
    requisitos: [
      'Informática intermediária e boa comunicação com usuários',
      'Noções de Windows, redes e Microsoft 365',
      'Organização para registrar chamados e documentar soluções',
      'Interesse por Azure Fundamentals e boas práticas de atendimento',
      'Vontade de aprender com times técnicos em projetos reais',
    ],
    atividades: [
      'Atender chamados de primeiro nível e orientar usuários',
      'Apoiar configuração de acessos, estações e ferramentas Microsoft',
      'Documentar problemas recorrentes e soluções aplicadas',
      'Acompanhar a equipe em rotinas de suporte e melhoria contínua',
    ],
  },
  {
    id: 'vaga-7',
    empresaId: 'empresa-1',
    titulo: 'Desenvolvedor Back-end .NET Júnior',
    nivel: 'Júnior',
    tipo: 'CLT',
    modalidade: 'Remoto',
    localizacao: 'Brasil',
    salario: 'R$ 3.000 - R$ 4.200',
    status: 'encerrada',
    publicadaEm: '2026-04-02',
    candidatos: 0,
    tags: ['dotnet', 'csharp', 'azure', 'api-rest', 'sql'],
    descricao:
      'Vaga antiga para atuar em APIs e integrações no ecossistema Microsoft. Ela permanece no gerenciamento, mas não entra nas vagas recentes do painel.',
    requisitos: [
      'Noções de C#, .NET e APIs REST',
      'Conhecimento básico de SQL',
      'Interesse por Azure e boas práticas de versionamento',
    ],
    atividades: [
      'Apoiar a manutenção de APIs internas',
      'Documentar integrações e corrigir pequenos bugs',
      'Participar de rituais ágeis com o time de engenharia',
    ],
  },
]

export const candidatosMock = [
  {
    id: 'cand-1',
    vagaId: 'vaga-1',
    nome: 'Lucas Andrade',
    status: 'Em andamento',
    cargo: 'Aluno em transição para TI',
    localizacao: 'Recife, PE',
    bio: 'Estudante focado em front-end, acessibilidade e construção de interfaces com React.',
    cursos: ['Front-end com HTML, CSS e JavaScript', 'Git e GitHub para Projetos'],
    tecnologias: ['React', 'JavaScript', 'HTML', 'CSS'],
  },
  {
    id: 'cand-2',
    vagaId: 'vaga-6',
    nome: 'Rafael Souza',
    status: 'Em andamento',
    cargo: 'Técnico de suporte',
    localizacao: 'Recife, PE',
    bio: 'Experiência com atendimento de usuários, hardware, redes e documentação técnica.',
    cursos: ['Informática Essencial', 'Git e GitHub para Projetos'],
    tecnologias: ['Suporte', 'Redes', 'Windows', 'Microsoft 365'],
  },
]
